services:

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ejbank
            MYSQL_PASSWORD: root
        ports:
          - 8005:3306
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8003:80

    app:
        build:
            context: .
            dockerfile: Dockerfile.windows
        links:
            - db:db
        ports:
            - 8001:8181
            - 8002:4848
            - 8004:9009
        depends_on:
            db:
                condition: service_healthy


